[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
amm = "9SqEGi3GLWjzF4aUtqyDZFS1tkobHBh6jkHM2DCxUkXq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
